### ISSUE TITLE
Error Exception: Add Master Template and Add a Header

### ISSUE THREAD

**Issue by Leirum** [mgeronimo/IOM-DTM#149] opened 2015-04-14 07:32 UTC
**Steps to replicate**
1. Navigate to Emergencies module.
2. Click the master template button on the upper right corner of the page.
3. Fill out all required fields in add emergency.
4.Click Save.
5. Add 3 Headers
6. Save Emergency.

**Actual Result**
ErrorException (E_UNKNOWN)
Undefined offset:

![35 1](https://cloud.githubusercontent.com/assets/9795882/7132350/fc9f4072-e2ba-11e4-9efa-d3422c2e2331.png)

![35 2](https://cloud.githubusercontent.com/assets/9795882/7132349/fc5d70b6-e2ba-11e4-9408-75f6d1f4bd10.png)

**Expected Result**
- It should display a validation message indicating "Survey has been updated successfully"
- Newly added header should not have an effect on adding new master template.

**Comment by barbacenasmc** [comment] 2015-04-24 06:32
Duplicate of issue #87

**Closed by barbacenasmc** 2015-04-24 06:32 UTC
Labels: Medium
