### ISSUE TITLE
Error Exception: Add Master Template and Add a Question

### ISSUE THREAD

**Issue by Leirum** [mgeronimo/IOM-DTM#142] opened 2015-04-14 06:19 UTC
**Steps to replicate**
1. Navigate to "Emergencies" list.
2. Click "Add Master Template" button on the upper right-corner of the screen.
3. Enter the name and description of the master template on the form.
4. Click "Add Emergency".
5. Once the edit page displays, hover the mouse cursor on the plus button hanging on the right side of the screen.
6. Click "Add Question".
7. Select a category.
8. Check all questions preferred to add.
9. Click "Add Question".
10. Scroll down to the bottom and click "Save Emergency".

**Actual Result**
ErrorException (E_UNKNOWN) Undefined offset: 

![add master temp- add question](https://cloud.githubusercontent.com/assets/9795882/7131352/c90c3562-e2b0-11e4-93f7-6c1d4a29fda3.png)

**Expected Result**
- Master template should be added successfully.
- A prompt should display saying "Survey has been updated successfully. "

**Comment by barbacenasmc** [comment] 2015-04-24 08:01
Duplicate of issue #87

**Closed by barbacenasmc** 2015-04-24 08:01 UTC
Labels: Medium
