### ISSUE TITLE
Error Exception: Edit Master Template and a

### ISSUE THREAD

**Issue by Leirum** [mgeronimo/IOM-DTM#153] opened 2015-04-14 08:24 UTC
**Steps to replicate**
1. Create a Master Template.
2. Create a child template.
3. Import all the question in the master template to child template.
4. Save the child template as final.
5. Click the Edit Icon in the Action Panel of the created master template.
6. Add questions in master template.

**Actual Result**
ErrorException (E_UNKNOWN)
Undefined offset: 

![39](https://cloud.githubusercontent.com/assets/9795882/7133106/791a1e40-e2c2-11e4-899c-5649267f3d7f.png)

**Expected Result**
- Master template should be updated successfully.
- User should be able to create another cycle template since there has been an added questions on the master template.

**Comment by barbacenasmc** [comment] 2015-04-24 06:13
Duplicate of issue no. #87

**Closed by barbacenasmc** 2015-04-24 06:13 UTC
Labels: Medium
