### ISSUE TITLE
Error Exception: Add Master Template: Delete a Question and Add a New One

### ISSUE THREAD

**Issue by Leirum** [mgeronimo/IOM-DTM#143] opened 2015-04-14 06:27 UTC
**Steps to replicate**
"1. Navigate to "Emergencies" list.
2. Click "Add Master Template" button on the upper right-corner of the screen.
3. Enter the name annd description of the master template on the form.
4. Click "Add Emergency".
5. Once the edit page displays, delete some existing questions.
6. Once the edit page displays, hover the mouse cursor on the plus button hanging on the right side of the screen.
7. Click "Add Question".
8. Select a category.
8. Check all questions preferred to add.
10. Click "Add Question".
11. Scroll down to the bottom and click "Save Emergency".

**Actual Result**
ErrorException (E_UNKNOWN)
Undefined offset: 168

![add master template- delete and add question](https://cloud.githubusercontent.com/assets/9795882/7131449/19d1ed9c-e2b2-11e4-9197-8fa7555e8f0f.png)

**Expected Result**
- Master template should be added successfully.
- A prompt should display saying "Survey has been updated successfully. "
- Only the remaining elements should be saved.

**Comment by barbacenasmc** [comment] 2015-04-24 08:01
Duplicate of issue #87

**Closed by barbacenasmc** 2015-04-24 08:01 UTC
Labels: Medium
